FORMAT: 1A

# Tinder
This guide was written by <a href="mailto:ally.dewar@adewra.com">Ally Dewar</a> of <a href="http://www.adewra.com">Adewra</a>, and is based off the original documentation written by <a href="http://rsty.org">Rich Taylor.
</a>

I have been exploring the Tinder HTTPS API in order to create a <a href="https://packagist.org/">PHP composer package</a> which can be used to interact with Tinder matches. You can find this package at https://github.com/Adewra/Tinder.

You can check out Rich Taylor’s original work from May 2014 at https://gist.github.com/rtt/10403467.

<br/>
####API Endpoints 
https://api.gotinder.com<br/>
Responsible for all data requests and responses

http://images.gotinder.com<br/>
Responsible for serving up images

https://etl.tindersparks.com<br/>
Responsible for data mining or analytics (presumably)

<br/>
####Required Request Headers
The following 3 headers are required on all requests made to the API;
*User-Agent*, *X-Auth-Token* and *Content-Type*.

In order to make any API calls you will need to have the X-Auth-Token header set with a Tinder Authentication Token. 

<br/>
####Optional Request Headers
There are a few optional headers which are sent from the Tinder application, I have listed them below purely for research purposes.

*App-Version*<br/>
I am not sure what this represents, as the version of the software used for analysis is 4.1.4, any input or guidance would be much appreciated. An example value is “218”.

*Platform*<br/>
This header is used to identify what platform/operating system you are querying from. An example value is “iOS”.

*OS_Version*<br/>
The above string represents iOS 8.1.3. An example value is “80000100003”.

<br/>
####Terminology
TBC

# Group Authentication
Failure to supply a Tinder Authentication Token, supplying an incorrect one or one which is out of date will result in a response with a HTTP Status Code of 500.

N.B. When first making a request for a Tinder Authentication Token, the X-Auth-Token header is ignored.

To extract the Facebook Access Token, visit https://www.facebook.com/dialog/oauth?client_id=464891386855067&redirect_uri=https://www.facebook.com/connect/login_success.html&scope=basic_info,email,public_profile,user_about_me,user_activities,user_birthday,user_education_history,user_friends,user_interests,user_likes,user_location,user_photos,user_relationship_details&response_type=token in your browser. It will redirect you to page saying ‘Success’ before redirecting you again to another page with a security warning and the token removed from the URL. To extract the access_token fragment from the URL you can launch your browsers Developer Tools and you can check the headers in there.


To find your Facebook ID for your profile you can use the tool at http://findmyfacebookid.com.

## Authentication [/auth]
### Retrieve Tinder authentication token [POST]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”

    + Body

            {
                "locale": "en-GB",
                "facebook_id": "4",
                "facebook_token": "EnEYhJBbcc-gm84CeUivNgC0bZZ"
            }

+ Response 200 (application/json)
    
    + Body
    
            {
                "token": "00000000-0000-4000-A000-000000000000",
                "user": {
                    "_id": "000000000000000000000000",
                    "active_time": "2015-02-27T12:00:00.000Z",
                    "create_date": "2015-02-27T12:00:00.000Z",
                    "age_filter_max": 26,
                    "age_filter_min": 18,
                    "api_token": "00000000-0000-4000-A000-000000000000",
                    "bio": "I'm probably single because I never forwarded those chain messages in 2003.\n\nI love going new places/travelling, tattoos, Italian food and comedy.",
                    "birth_date": "1990-02-27T00:00:00.000Z",
                    "distance_filter": 12,
                    "full_name": "Johnny Appleseed",
                    "groups": ["plus_subscription_299"],
                    "gender": 0,
                    "gender_filter": 1,
                    "name": "Johnny",
                    "ping_time": "2015-02-26T16:57:22.134Z",
                    "discoverable": true,
                    "photos": [{
                        "url": "http://images.gotinder.com/000000000000000000000000/00000000-0000-4000-A000-000000000000.jpg",
                        "processedFiles": [{
                            "url": "http://images.gotinder.com/000000000000000000000000/640x640_00000000-0000-4000-A000-000000000000.jpg",
                            "height": 640,
                            "width": 640
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/320x320_00000000-0000-4000-A000-000000000000.jpg",
                            "height": 320,
                            "width": 320
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/172x172_00000000-0000-4000-A000-000000000000.jpg",
                            "height": 172,
                            "width": 172
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/84x84_00000000-0000-4000-A000-000000000000.jpg",
                            "height": 84,
                            "width": 84
                        }],
                        "extension": "jpg",
                        "fbId": "00000000000000000",
                        "fileName": "00000000-0000-4000-A000-000000000000.jpg",
                        "main": false,
                        "ydistance_percent": 1,
                        "yoffset_percent": 0,
                        "xoffset_percent": 0,
                        "id": "00000000-0000-4000-A000-000000000000",
                        "xdistance_percent": 1
                    }, {
                        "url": "http://images.gotinder.com/000000000000000000000000/00000000-0000-4000-A000-000000000001.jpg",
                        "processedFiles": [{
                            "url": "http://images.gotinder.com/000000000000000000000000/640x640_00000000-0000-4000-A000-000000000001.jpg",
                            "height": 640,
                            "width": 640
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/320x320_00000000-0000-4000-A000-000000000001.jpg",
                            "height": 320,
                            "width": 320
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/172x172_00000000-0000-4000-A000-000000000001.jpg",
                            "height": 172,
                            "width": 172
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/84x84_00000000-0000-4000-A000-000000000001.jpg",
                            "height": 84,
                            "width": 84
                        }],
                        "extension": "jpg",
                        "fbId": "0000000000001",
                        "fileName": "00000000-0000-4000-A000-000000000001.jpg",
                        "main": false,
                        "ydistance_percent": 0.75,
                        "yoffset_percent": 0.1253906,
                        "xoffset_percent": 0,
                        "id": "00000000-0000-4000-A000-000000000001",
                        "xdistance_percent": 1
                    } , {
                        "url": "http://images.gotinder.com/000000000000000000000000/00000000-0000-4000-A000-000000000002.jpg",
                        "processedFiles": [{
                            "url": "http://images.gotinder.com/000000000000000000000000/640x640_00000000-0000-4000-A000-000000000002.jpg",
                            "height": 640,
                            "width": 640
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/320x320_00000000-0000-4000-A000-000000000002.jpg",
                            "height": 320,
                            "width": 320
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/172x172_00000000-0000-4000-A000-000000000002.jpg",
                            "height": 172,
                            "width": 172
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/84x84_00000000-0000-4000-A000-000000000002.jpg",
                            "height": 84,
                            "width": 84
                        }],
                        "extension": "jpg",
                        "fbId": "0000000000002",
                        "fileName": "00000000-0000-4000-A000-000000000002.jpg",
                        "main": false,
                        "ydistance_percent": 1,
                        "yoffset_percent": 0,
                        "xoffset_percent": 0.1243915,
                        "id": "00000000-0000-4000-A000-000000000002",
                        "xdistance_percent": 0.7510431
                    }],
                    "purchases": []
                },
                "versions": {
                    "active_text": "0.0.0",
                    "age_filter": "2.1.0",
                    "matchmaker": "2.1.0",
                    "trending": "10.0.0",
                    "trending_active_text": "10.0.0"
                },
                "globals": {
                    "friends": true,
                    "invite_type": "client",
                    "recs_interval": 20000,
                    "updates_interval": 2000,
                    "recs_size": 40,
                    "matchmaker_default_message": "I want you to meet someone. I introduced you on Tinder www.gotinder.com/app",
                    "share_default_text": "<style>body{color:#fff;text-align:center;font-family:HelveticaNeue;text-shadow:0 1px 1px rgba(0,0,0,0.63);}h1{font-size:24px;line-height:24px;margin:0;}p{font-size:16px;margin:8px;}</style><h1>Get a Boost</h1><p><strong>Invite friends</strong> to show up <br/><strong>even higher</strong> in recommendations.</p>",
                    "boost_decay": 180,
                    "boost_up": 7,
                    "boost_down": 8,
                    "sparks": false,
                    "kontagent": false,
                    "sparks_enabled": false,
                    "kontagent_enabled": false,
                    "mqtt": false,
                    "tinder_sparks": true,
                    "moments_interval": 30000,
                    "plus": true
                }
            }

# Group Current User

This information relates to the user that is currently signed into the application. If you want to query another user, please check out the section titled Other Persons.

## Profile [/user]
### Create a new account [PUT]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”
            X-Auth-Header: “00000000-0000-4000-A000-000000000000”

    + Body

            {
                "status": 200,
            }

+ Response 200 (application/json)
    
    + Body
    
            {

            }
            
### Retrieve current user's profile [GET]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”
            X-Auth-Header: “00000000-0000-4000-A000-000000000000”

    + Body

            {
            
            }

+ Response 200 (application/json)
    
    + Body
    
            {

            }

### Update current user's profile [POST]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”
            X-Auth-Header: “00000000-0000-4000-A000-000000000000”

    + Body

            {
            
            }

+ Response 200 (application/json)
    
    + Body
    
            {

            }
            
### Delete current user's profile [DELETE]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”
            X-Auth-Header: “00000000-0000-4000-A000-000000000000”

    + Body

            {
                "status": 200,
            }

+ Response 200 (application/json)
    
    + Body
    
            {

            }
            
## Moments [/user/moments]
### Create a new moment [POST]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”
            X-Auth-Header: “00000000-0000-4000-A000-000000000000”

    + Body

            {
            
            }

+ Response 200 (application/json)
    
    + Body
    
            {

            }
            
### Retrieve current user's posted moments [GET]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”
            X-Auth-Header: “00000000-0000-4000-A000-000000000000”

    + Body

            {
            
            }

+ Response 200 (application/json)
    
    + Body
    
            {

            }
            
## Recommendations [/user/recs{?locale}]
### Retrieve current user's recommendations [GET]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”
            X-Auth-Header: “00000000-0000-4000-A000-000000000000”

    + Body

            {

            }

+ Response 200 (application/json)
    
    + Body
    
            {
                "status": 200,
                "results": []
            }
            
## Ping [/user/ping]
### Update Current User's Location [POST]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”
            X-Auth-Header: “00000000-0000-4000-A000-000000000000”

    + Body

            {
            
            }

+ Response 200 (application/json)
    
    + Body
    
            {

            }
            
## Updates [/updates]
### Retrieve changes since last update [POST]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”
            X-Auth-Header: “00000000-0000-4000-A000-000000000000”

    + Body

            {
            
            }

+ Response 200 (application/json)
    
    + Body
    
            {
                {
                    "matches": [],
                    "blocks": [],
                    "matchmaker": [],
                    "lists": [],
                    "deleted_lists": [],
                    "last_activity_date": "2015-02-27T00:00:00.000Z"
                }
            }
          
# Group Other Persons

If you want to query the currently logged in user, please check out the section titled Current User.

## Profile [/user/{identifier}]
### Retrieve other person's profile [GET]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”
            X-Auth-Header: “00000000-0000-4000-A000-000000000000”

    + Body

            {
            
            }

+ Response 200 (application/json)
    
    + Body
    
            {
                "status": 200,
                "results": [{
                }]
            } 
            
# Group Swiping
## Like [/like/{identifier}]
### Like a Person's Profile [GET]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”
            X-Auth-Header: “00000000-0000-4000-A000-000000000000”

    + Body

            {
            
            }

+ Response 200 (application/json)
    
    + Body
    
            {

                "match": false,
                "likes_remaining": 100
            }

## Pass [/pass/{identifier}]
### Pass a person's profile [GET]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”
            X-Auth-Header: “00000000-0000-4000-A000-000000000000”

    + Body

            {
                "status": 200,
            }

+ Response 200 (application/json)
    
    + Body
    
            {

            }
            
# Group Moments
## Moments [/feed/moments]
### Retrieve matches moments [GET]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”
            X-Auth-Header: “00000000-0000-4000-A000-000000000000”

    + Body

            {
            
            }

+ Response 200 (application/json)
    
    + Body
    
            {

            }
            
## Moment Likes [/feed/likes]
### Retrieve matches likes of current users moments [GET]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”
            X-Auth-Header: “00000000-0000-4000-A000-000000000000”

    + Body

            {
            
            }

+ Response 200 (application/json)
    
    + Body
    
            {

            }
            
# Group Reporting
## Report [/report/{identifier}{?cause}]
### Report a person's profile [POST]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”
            X-Auth-Header: “00000000-0000-4000-A000-000000000000”

    + Body

            {
            
            }

+ Response 200 (application/json)
    
    + Body
    
            {

            }
            
# Group Other
## Metadata [/meta]
### Retrieve Tinder application's metadata [GET]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”
            X-Auth-Header: “00000000-0000-4000-A000-000000000000”

    + Body

            {
            
            }

+ Response 200 (application/json)
    
    + Body
    
            {
                "status": 200,
                "notifications": [],
                "groups": [{
                "type": "purchase",
                "key": "plus_subscription_299",
                "sub_type": "plus"
                }],
                "rating": {
                    "likes_remaining": 100
                },
                "travel": {
                    "is_traveling": false
                },
                "purchases": [],
                "versions": {
                    "active_text": "0.0.0",
                    "age_filter": "2.1.0",
                    "matchmaker": "2.1.0",
                    "trending": "10.0.0",
                    "trending_active_text": "10.0.0"
                },
                "globals": {
                    "invite_type": "client",
                    "recs_interval": 20000,
                    "updates_interval": 2000,
                    "recs_size": 40,
                    "matchmaker_default_message": "I want you to meet someone. I introduced you on Tinder www.gotinder.com/app",
                    "share_default_text": "<style>body{color:#fff;text-align:center;font-family:HelveticaNeue;text-shadow:0 1px 1px rgba(0,0,0,0.63);}h1{font-size:24px;line-height:24px;margin:0;}p{font-size:16px;margin:8px;}</style><h1>Get a Boost</h1><p><strong>Invite friends</strong> to show up <br/><strong>even higher</strong> in recommendations.</p>",
                    "boost_decay": 180,
                    "boost_up": 7,
                    "boost_down": 8,
                    "sparks": false,
                    "kontagent": false,
                    "sparks_enabled": false,
                    "kontagent_enabled": false,
                    "mqtt": false,
                    "tinder_sparks": true,
                    "moments_interval": 30000,
                    "ad_swipe_interval": 5,
                    "plus": true
                },
                "user": {
                    "_id": "000000000000000000000000",
                    "active_time": "2015-02-27T12:00:00.000Z",
                    "create_date": "2015-02-27T12:00:00.000Z",
                    "age_filter_max": 26,
                    "age_filter_min": 18,
                    "api_token": "00000000-0000-4000-A000-000000000000",
                    "bio": "I'm probably single because I never forwarded those chain messages in 2003.\n\nI love going new places/travelling, tattoos, Italian food and comedy.",
                    "birth_date": "1990-02-27T00:00:00.000Z",
                    "distance_filter": 12,
                    "full_name": "Johnny Appleseed",
                    "groups": ["plus_subscription_299"],
                    "gender": 0,
                    "gender_filter": 1,
                    "name": "Johnny",
                    "photos": [{
                        "url": "http://images.gotinder.com/000000000000000000000000/00000000-0000-4000-A000-000000000000.jpg",
                        "processedFiles": [{
                            "url": "http://images.gotinder.com/000000000000000000000000/640x640_00000000-0000-4000-A000-000000000000.jpg",
                            "height": 640,
                            "width": 640
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/320x320_00000000-0000-4000-A000-000000000000.jpg",
                            "height": 320,
                            "width": 320
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/172x172_00000000-0000-4000-A000-000000000000.jpg",
                            "height": 172,
                            "width": 172
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/84x84_00000000-0000-4000-A000-000000000000.jpg",
                            "height": 84,
                            "width": 84
                        }],
                        "extension": "jpg",
                        "fbId": "00000000000000000",
                        "fileName": "00000000-0000-4000-A000-000000000000.jpg",
                        "main": false,
                        "ydistance_percent": 1,
                        "yoffset_percent": 0,
                        "xoffset_percent": 0,
                        "id": "00000000-0000-4000-A000-000000000000",
                        "xdistance_percent": 1
                    }, {
                        "url": "http://images.gotinder.com/000000000000000000000000/00000000-0000-4000-A000-000000000001.jpg",
                        "processedFiles": [{
                            "url": "http://images.gotinder.com/000000000000000000000000/640x640_00000000-0000-4000-A000-000000000001.jpg",
                            "height": 640,
                            "width": 640
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/320x320_00000000-0000-4000-A000-000000000001.jpg",
                            "height": 320,
                            "width": 320
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/172x172_00000000-0000-4000-A000-000000000001.jpg",
                            "height": 172,
                            "width": 172
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/84x84_00000000-0000-4000-A000-000000000001.jpg",
                            "height": 84,
                            "width": 84
                        }],
                        "extension": "jpg",
                        "fbId": "0000000000001",
                        "fileName": "00000000-0000-4000-A000-000000000001.jpg",
                        "main": false,
                        "ydistance_percent": 0.75,
                        "yoffset_percent": 0.1253906,
                        "xoffset_percent": 0,
                        "id": "00000000-0000-4000-A000-000000000001",
                        "xdistance_percent": 1
                    } , {
                        "url": "http://images.gotinder.com/000000000000000000000000/00000000-0000-4000-A000-000000000002.jpg",
                        "processedFiles": [{
                            "url": "http://images.gotinder.com/000000000000000000000000/640x640_00000000-0000-4000-A000-000000000002.jpg",
                            "height": 640,
                            "width": 640
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/320x320_00000000-0000-4000-A000-000000000002.jpg",
                            "height": 320,
                            "width": 320
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/172x172_00000000-0000-4000-A000-000000000002.jpg",
                            "height": 172,
                            "width": 172
                        }, {
                            "url": "http://images.gotinder.com/000000000000000000000000/84x84_00000000-0000-4000-A000-000000000002.jpg",
                            "height": 84,
                            "width": 84
                        }],
                        "extension": "jpg",
                        "fbId": "0000000000002",
                        "fileName": "00000000-0000-4000-A000-000000000002.jpg",
                        "main": false,
                        "ydistance_percent": 1,
                        "yoffset_percent": 0,
                        "xoffset_percent": 0.1243915,
                        "id": "00000000-0000-4000-A000-000000000002",
                        "xdistance_percent": 0.7510431
                    }],
                    "ping_time": "2015-02-27T00:00:00.000Z",
                }
            }
            
## Assets [/assets]
### Retrieve Tinder application's assets [GET]
+ Request (application/json)

    + Headers

            User-Agent: “Tinder/4.1.4 (iPhone; iOS 8.1.3; Scale/2.00)”
            X-Auth-Header: “00000000-0000-4000-A000-000000000000”

    + Body

            {
            
            }

+ Response 200 (application/json)
    
    + Body
    
            {

            }
            
# Group Matchmaking
The matchmaking feature has now been depreciated.